// Supabase Configuration
// This file is automatically generated when connecting to Supabase project
// Project ID: ypydtfxqorpjqjferecz

class SupabaseConfig {
  static const String supabaseUrl = 'https://ypydtfxqorpjqjferecz.supabase.co';
  static const String supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlweWR0Znhxb3JwanFqZmVyZWN6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIxNzM2MzMsImV4cCI6MjA3Nzc0OTYzM30.z4URSVEm50S1p-nShHnWDfs-YaaGkE18Hl5YT7GHsRs';
}
